version: "3.8"

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "127.0.0.1:3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: codecamp
      MYSQL_DATABASE: banking
      TZ: Asia/Jakarta
    volumes:
      - mysqldata:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    restart: always

volumes:
  mysqldata: